### ISSUE TITLE
ChainProvider does not have viewOptions props

### ISSUE THREAD

**Issue by grikomsn** [cosmology-tech/cosmos-kit#110]
Compared to `WalletProvider`, apparently `ChainProvider` does not expose `viewOptions` on the provider component. The commented line does not explain the reason. It would be great if it's exposed so that it has the same behavior as `WalletProvider`.

https://github.com/cosmology-tech/cosmos-kit/blob/2e3cee6fb21229f174c31511c6ada850fb5cdae8/packages/react/src/provider-v2.tsx#L30-L52

**Comment by pyramation** [comment]
Thanks @grikomsn ! 

I believe the corner-cases for `useChain` compared with `useWallet` were a bit more complex from a UI/UX standpoint, so we're holding off on this, but it's on our radar! thanks for pointing it out and we will prioritize this one

**Comment by liujun93** [comment]
@grikomsn 

```
interface ViewOptions {
  alwaysOpenView?: boolean;
  closeViewWhenWalletIsConnected?: boolean;
  closeViewWhenWalletIsDisconnected?: boolean;
  closeViewWhenWalletIsRejected?: boolean;
}
```

 We found it's a little bit unfitted for these `viewOptions` and `useChain`. i.e. It's hard to decide closing modal or not if some chains is connected but some are rejected. Since multi-chains are allowed to connect at same time, there are cases that `viewOptions` have conflicts with each other. Therefore we suggest using `closeView` function to make users decide closing or not. Docs can be seen here.

https://docs.cosmoskit.com/use-chain#methods

:)
