### ISSUE TITLE
remove react-icons from any non-react packages

### ISSUE THREAD

**Issue by pyramation** [cosmology-tech/cosmos-kit#136]
perhaps we need to use string names? not sure how to resolve this yet, but we apparently have react-icons in non-react packages.

**Comment by liujun93** [comment]
- In `core` it's `IconType` needed
- in wallet packages `react-icons` is needed for download infos. but i removed the integrating wallets i.e. keplr after the wallet split since they don't have any registry object

**Comment by pyramation** [comment]
let's imagine a new way to manage it, so when we support non-react frameworks we don't force react packages onto users.

maybe we can use icon name as a string, and make icon adapters later? any ideas?

**Comment by j0nl1** [comment]
Hey! I would like to join into the conversation and help to figure out the best way to handle this situation.

Recently I've doing optimizations in the frontend side in order to reduce load times. I notice that for example react-icons is like [~90%](https://bundlephobia.com/package/@cosmos-kit/vectis@0.14.21) of the bundle size in @cosmos-kit/vectis

What about using pure SVG instead of using react icons? in that way it will also supported by other frameworks that are not react.

**Comment by gjermundgaraba** [comment]
> Want to note - I think core is now free of react - could be removed from package.json

I don't think that is the case: https://github.com/cosmology-tech/cosmos-kit/blob/main/packages/core/src/types/wallet.ts

I was looking to see if I could re-use the core package for another component I am building, but I cannot (and/or wont) as long as it has any react libraries

**Comment by pyramation** [comment]
this is on our list! wrapping up a few more items and this will be next 🛠

**Comment by liujun93** [comment]
@j0nl1 @TrevorJTClarke @gjermundgaraba @pyramation `react-icons` and `react` has been removed from `@cosmos-kit/core` and all CosmosKit wallet packages in the latest version. Thank you guys!
