### ISSUE TITLE
WalletConnect V2 Browser Errors

### ISSUE THREAD

**Issue by JoseRFelix** [cosmology-tech/cosmos-kit#180]
## Description

When trying to connect with Keplr mobile through WalletConnect, cryptic errors are often thrown, leading to failed connections. 

### `Error: No matching key. history: 1682369331591554.` 

1. Start this repo `package/example`dev server.
2. Click on `connect wallet`
3. Click on Keplr Mobile wallet
4. Scan QR with Keplr wallet
5. Disconnect but keep Keplr Mobile Wallet open
6. Refresh website
7. Try to connect to Keplr Mobile again

### `Error: Chain {chain_id} is not connected yet, please check the session approval namespaces.`

This error is coming from the WalletConnect Sign client.

1. Start this repo's `package/example`dev server.
2. Click on `connect wallet`
3. Click on Keplr Mobile wallet
4. Scan QR with Keplr wallet 

## Possible solutions

- [ ] Update WalletConnect client's version in `packages/walletconnect`
- [ ] Allow catching errors so users can try reconnecting. Currently, errors get thrown globally.

**Comment by liujun93** [comment]
@JoseRFelix 

> Error: No matching key. history: 1682369331591554.

Fixed. (Remember also upgrade @cosmos-kit/core.)

Btw, there are Errors from walletconnect emitter that we cannot catch from CosmosKit side. Except that, we'll always catch errors so that users can try reconnecting when it's WalletStatus.Error.

> Error: Chain {chain_id} is not connected yet, please check the session approval namespaces.

This error is from CosmosKit and it means you're requesting chain address that not approved in session. If you're building session manually by calling `walletClient.connect(chainIds: string | string[])`, make sure the target `chainId` is included in `connect` argument
