### ISSUE TITLE
[Bug] Not detect account changed when mount

### ISSUE THREAD

**Issue by j0nl1** [cosmology-tech/cosmos-kit#214]
I detect a bug where an user login into dApp X and connect with account A, if after these close dApp X and change its account to B and access again to dApp X, it assume the account is the same since it recover the information from local storage. 

I think the expected behavior would be to recover this information and check it using the same account, if not login with new account.

https://github.com/cosmology-tech/cosmos-kit/assets/40375118/826cce10-406e-442b-8521-5d7210260753

**Comment by pyramation** [comment]
So the reason it didn't get the subscription to account change is because the window was changed. 

What was the issue again @liujun93 with requesting account info on page load? I think keplr will pop open an unnecessary window?

maybe we can look at what the current osmosis app is doing and see if we need to change some logic to allow for fetching/verifying current account on page load in a non invasive way.

**Comment by liujun93** [comment]
@pyramation this issue has been fixed because I found there is no unnecessary popup now.

**Comment by pyramation** [comment]
ok great!
