### ISSUE TITLE
remove `chain-registry` from web3auth peerDeps

### ISSUE THREAD

**Issue by pyramation** [cosmology-tech/cosmos-kit#269]
should only require chain-registry/types not the actual full-blown registry 

cc @NoahSaso

**Comment by NoahSaso** [comment]
i use it [here](https://github.com/cosmology-tech/cosmos-kit/blob/beta/wallets/web3auth/src/extension/client.ts#L162) because i need to be able to derive the address from the public key in the signer using the bech32 prefix of the chain.

where am i supposed to find the client object for a given chain ID inside the main client?

**Comment by pyramation** [comment]
you should import the types instead, and require that users load their chains, e.g.:

```ts
import { AssetList, Chain } from '@chain-registry/types';
```

and then make a function or constructor that accepts them as arguments. Cosmos Kit already has them, so you could likely get them from the wallet manager:

https://github.com/cosmology-tech/cosmos-kit/blob/8e9c0843d8ca1a5fb7508c92dab67bff1169d01e/packages/core/src/manager.ts#L44-L45
