### ISSUE TITLE
cosmos-kit bundle depends on bip39, I don't think it should

### ISSUE THREAD

**Issue by ValarDragon** [cosmology-tech/cosmos-kit#329]
The cosmos-kit bundle brings in bip39, which is a 72kb gzipped, 480kb parsed import size.

This shouldn't be getting bundled at all though, since I can't see a reason as to why cosmos-kit would touch mnemonics. We should figure out how to get this out of the bundle. Downstream, I am trying to replace bip39 with bip39-light in the interrim, but the ideal would just be deleting this all together.

(Replacing with a no-op is causing a build error somewhere)

**Comment by liujun93** [comment]
@ValarDragon that probably because we have some peerDependencies on `cosmjs`. https://github.com/cosmology-tech/cosmos-kit/blob/2a3379301a9db374de73010d2f6f50d99f92b3cf/packages/core/package.json#L83-L87

we don't explicitly depend on bip39.

we're working on removing the dependency on `cosmjs`. I believe it'll get smaller after the removal.
