### ISSUE TITLE
Keplr wallet connect execute msgs not working (Safari & Chrome Mobile<->Keplr Mobile)

### ISSUE THREAD

**Issue by ghost** [cosmology-tech/cosmos-kit#72]
Keplr wallet connect says "Not yet implemented" when trying to execute a contract msg. Though using deep linking on DAODAO, they successfully are able to prompt keplr to sign a tx. 

https://forecast.deliverdao.org/
leverages cosmos-kit, so likely a difference in implementation between daodao and cosmos-kit

https://user-images.githubusercontent.com/95767439/200077194-d8408d31-0ddc-4377-810e-49e77e7566b1.mov

**Comment by pyramation** [comment]
Thank you! We're looking into this and should have it sorted out soon!

**Comment by pyramation** [comment]
Since DaoDao works @liujun93 let's take a look at what they do for executing messages

- https://github.com/noahsaso/cosmodal
- https://github.com/DA0-DA0/dao-dao-ui/blob/a2cc5f754e1b668926ef66532be60501d7762cdb/apps/dapp/package.json#L30

hey @NoahSaso — do you know where the code is that creates the TX? I'm curious if there's anything specific we need to do to support Safari Mobile -> Keplr TXs

**Comment by professionallyatortoise** [comment]
Chrome mobile doesn't work either just tried it btw

**Comment by pyramation** [comment]
@liujun93 
- [this is the wallet connect keplr client we are importing here](https://github.com/chainapsis/keplr-wallet/blob/master/packages/wc-client/src/index.ts)
- [this is the wallet connect that cosmodal was using here](https://github.com/NoahSaso/cosmodal/blob/main/src/connectors/walletconnect-keplr.ts) 

Let's also find out what function is throwing "not yet implemented", we may be calling experimentalSuggestChain in mobile mode which we're not supposed to (although I doubt in this case since Juno is supported), however, we should test it and [look at what Noah did w the cosmodal here](https://github.com/NoahSaso/cosmodal/blob/bfce45c32fb1d69642f5a023b2efa55c18bbe56a/src/utils/getConnectedWalletInfo.ts#L15-L19)

**Comment by pyramation** [comment]
for testing @liujun93 let's use https://daodao.zone/ for mobile as our inspiration 

- [ ] create a Dao using JUNO
- [ ] invite Dan and Irene to the Dao
- [ ] let's use this Dao for testing
