### ISSUE TITLE
when using default modal Chakra theme being overwritten

### ISSUE THREAD

**Issue by vexxvakan** [cosmology-tech/cosmos-kit#80]
I just updated to the latest version of cosmos-kit and found out, that your ChakraProvider used in the modal overrides my custom theme entirely. I even replaced the modal with a custom one and it still overrides my entire chakra config. Any ideas?

**Comment by vexxvakan** [comment]
Okay, after some sleep and a restart this all calmed down. Themes are now working as expected though that was indeed very weird. 

What still stands is, if you use the default wallet modal any chakra theme in the dApp is being overwritten by your theme. This is not the case for other chakra modules though...

**Comment by pyramation** [comment]
Thanks @vexxvakan ! We'll take a look at this ASAP!

I'll rename the issue to reflect that it's mostly isolated to using the default modal

**Comment by liujun93** [comment]
Thanks! @vexxvakan This problem has been fixed in the latest version, which is `@cosmos-kit/react@0.24.8`

btw, the theme in modal is added in case users don't use `chakra` in their app. For the latest version, chakra theme in app won't be overwritten by the modal theme, but the modal theme keeps the same with app.

Enjoy CosmosKit! 😉
