### ISSUE TITLE
styles are being overridden

### ISSUE THREAD

**Issue by pyramation** [cosmology-tech/cosmos-kit#90]
## tailwind styles overridden

since it has been indicated that tailwind styles don't break when using 0.24.7, seems that the commit after this one: https://github.com/cosmology-tech/cosmos-kit/commit/02ba6b02c2bb4fa4f32edf5574a5e50a755b30e8

which is this one: https://github.com/cosmology-tech/cosmos-kit/commit/3afd3e868ae7533dc6072e74b1732bd25ee5be7c

could likely be the reason why styles are being overridden

![Screen Shot 2022-11-22 at 9 44 21 PM](https://user-images.githubusercontent.com/545047/203478377-135e9632-8615-4bdb-aae8-c2301cf2fc6e.png)

**Comment by pyramation** [comment]
## chakra styles being overriden

 these versions work:

```
"@cosmos-kit/core": "0.25.1",
"@cosmos-kit/cosmostation": "0.11.0",
"@cosmos-kit/keplr": "0.29.0",
"@cosmos-kit/react": "0.24.8",
```

these do NOT work

```
"@cosmos-kit/core": "^0.26.1",
"@cosmos-kit/cosmostation": "^0.12.1",
"@cosmos-kit/keplr":"^0.30.1",
"@cosmos-kit/react": "^0.25.1",
```

**Comment by findolor** [comment]
I've just realized the issue is not with tailwind at all.

If you look at the example repo here https://github.com/findolor/cosmo-kit-tailwind-test, it uses tailwind to change the text font in `index.tsx`. That font still changes even if we wrap the app with `WalletProvider`.

The issue is with the `global.css` file. I've defined the background color as red but when the app is wrapped with `WalletProvider` it changes to a different color than red.

## With WalletProvider
<img width="1512" alt="Screenshot 2022-11-23 at 10 32 54" src="https://user-images.githubusercontent.com/16416963/203492802-76ce220c-f0ba-4c76-8ca0-71d93b3bd709.png">

## Without WalletProvider
<img width="1512" alt="Screenshot 2022-11-23 at 10 33 12" src="https://user-images.githubusercontent.com/16416963/203492827-5d41425e-4bbf-4a74-9ae7-852de13fd43f.png">

**Comment by pyramation** [comment]
## tailwind

seems that chakra is the cultprit of this one

```js
export default function App({ Component, pageProps }: AppProps) {
  return (
    <ChakraProvider theme={defaultTheme}>
    {/* <WalletProvider wallets={wallets} chains={chains} assetLists={assets}> */}
      <Component {...pageProps} />
    {/* </WalletProvider> */}
    </ChakraProvider>
  )
}
```

**Comment by pyramation** [comment]
are we're not 100% sure we're not nesting Chakra Providers? https://github.com/chakra-ui/chakra-ui/discussions/5180 
cc @liujun93

**Comment by liujun93** [comment]
@findolor This bug has been fixed. You can upgrade to the latest cosmos-kit and check it. Thanks for finding the problem. Have fun! ^-^

**Comment by findolor** [comment]
@liujun93 Thanks for the quick fix! Happy to help in any way 🚀
